import Image from "next/image";
import AuthImage from '@/public/auth-image.png'
import { Metadata } from "next";


export const metadata: Metadata = {
    title: "Auth | Mobbin",
    description: "Generated by create next app",
  };
  


export default function AuthLauout({ children }: { children: React.ReactNode }) {

    return(
        <div className="flex flex-row items-center w-full justify-center">
            
            <main className="w-[50%] flex flex-col items-center justify-center h-[100vh]">
            {children}
            </main>

            <div className="flex flex-col items-center justify-center h-[100vh] w-[50%]">
                <Image src={AuthImage} alt="authImage" width={500} height={500} className="w-full h-[100vh] text-[var(--foreground)]"/>
            </div>
        </div>
    )
}