import MyApps from "@/components/ios/MyApps";
import Navbar from "@/components/navbar/Navbar"
import { Metadata } from "next";


export const metadata: Metadata = {
    title: "Discover iOS, Android, and Web Apps | Mobbin",
    description: "Generated by create next app",
  };

export default function AppLayout({ children } : { children: React.ReactNode }) {
    return (

        <div>
            <div className='container'>
                <h1 className='mb-6 mt-16'>Discover</h1>
            </div>
            <MyApps />
            <main>{children}</main>
        </div>
    )
}