import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/provider";

const saans = localFont({
  src: "./font/Saans-Regular.woff",
  variable: "--font-saans-sans",
  weight: "100 900",
});

const saansBold = localFont({
  src: "./font/Saans-medium.woff",
  variable: "--font-saans-sans",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${saans.variable} ${saansBold.variable} $ antialiased`}
      >
        <Providers>{children}</Providers>
        
      </body>
    </html>
  );
}
